name: Build and Publish JAR

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run tests
      run: ./gradlew test

    - name: Build shadow JAR
      run: ./gradlew shadowJar

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdfcli-jar
        path: build/libs/pdfcli.jar
        retention-days: 30

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: pdfcli-jar
        path: ./

    - name: Upload JAR to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pdfcli.jar
        asset_name: pdfcli.jar
        asset_content_type: application/java-archive